config/routes.rb
Rails.application.routes.draw do
  resources :mapas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "bemvindos#index"
  resources :services
  resources :clients
  match '/contacts',  to: 'contacts#new', via:'get'
  resources "contacts", only: [:new, :create]
  get '/about' => 'bemvindos#about'
end
	

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message

def headers
	{
:subject =>  "Basler Website",
:to => "basler.2001@gmail.com",
:from => %("#{name}" <#{email}>)
}
end
end

app/models/mapa.rb
class Mapa < ApplicationRecord
	geocoded_by :address
	after_validation :geocode
end
	

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  add_flash_types :danger, :info, :warning, :success
end

app/controllers/bemvindos_controller.rb
class BemvindosController < ApplicationController

def index
end

def about
end

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
	def index
	end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
 
 def new
 	@contact = Contact.new
 end

 def create
    @contact = Contact.new(params[:contact])
 	@contact.request = request
 	if @contact.deliver
 		redirect_to  root_path, success: "Obrigado por enviar a mensagem. Entraremos em contacto consigo em breve"
 		puts "it sended"
 	else 
 		render :new, danger: "Não foi possivel enviar a mensagem."
 		puts "it did not sended"
 	end
 end
end

app/controllers/mapas_controller.rb
class MapasController < ApplicationController
  before_action :set_mapa, only: [:show, :edit, :update, :destroy]

  # GET /mapas
  # GET /mapas.json
  def index
    @mapas = Mapa.all
@hash = Gmaps4rails.build_markers(@mapas) do |mapa, marker|
  marker.lat mapa.latitude
  marker.lng mapa.longitude
end
  end

  # GET /mapas/1
  # GET /mapas/1.json
  def show
  end

  # GET /mapas/new
  def new
    @mapa = Mapa.new
  end

  # GET /mapas/1/edit
  def edit
  end

  # POST /mapas
  # POST /mapas.json
  def create
    @mapa = Mapa.new(mapa_params)

    respond_to do |format|
      if @mapa.save
        format.html { redirect_to @mapa, notice: 'Mapa was successfully created.' }
        format.json { render :show, status: :created, location: @mapa }
      else
        format.html { render :new }
        format.json { render json: @mapa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mapas/1
  # PATCH/PUT /mapas/1.json
  def update
    respond_to do |format|
      if @mapa.update(mapa_params)
        format.html { redirect_to @mapa, notice: 'Mapa was successfully updated.' }
        format.json { render :show, status: :ok, location: @mapa }
      else
        format.html { render :edit }
        format.json { render json: @mapa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mapas/1
  # DELETE /mapas/1.json
  def destroy
    @mapa.destroy
    respond_to do |format|
      format.html { redirect_to mapas_url, notice: 'Mapa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mapa
      @mapa = Mapa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mapa_params
      params.require(:mapa).permit(:latitude, :longitude, :address, :description, :title)
    end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bemvindos_helper.rb
module BemvindosHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/i18n_helper.rb
module I18nHelper
  def translate(key, options={})
    super(key, options.merge(raise: true))
  rescue I18n::MissingTranslationData
    key
  end
  alias :t :translate
end

app/helpers/mapas_helper.rb
module MapasHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/bemvindos/about.html.erb
<br>
<br>
<br>
<br>
<body>
<div id="filler">
BASLER, é uma empresa privada, de direito 100% Angolano, fundada em 2001.<br>
<br>
Sendo uma empresa relativamente recente a BASLER reúne uma equipa técnica com experiência nas TI em angola que remonta aos últimos oito anos,<br> abarcando as mais diversas áreas das Tecnologias de Informação e Telecomunicações. <br>
<br>
Experiência acumulada pelos anos de trabalho no ramo a BASLER oferecem a garantia da prestação de serviços da mais alta qualificação.<br>
<br>
Ciente de que o seu sucesso depende do sucesso dos seus clientes, mais do que um mero prestador de serviços, a <br>BASLER posiciona-se como um verdadeiro parceiro de negócio, tendo uma actuação que tem como objectivo compreender<br> as necessidades tecnológicas dos clientes e assumindo um compromisso constante tendo em vista a satisfação dessas necessidades<br>
</div>
</body>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

app/views/bemvindos/index.html.erb
<HTML>
<HEAD>
 <%= stylesheet_link_tag    'bemvindos', media: 'all', 'data-turbolinks-track': 'reload' %>
   <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

</HEAD>
<BODY>
<div id="filler">
<strong>Apostamos em pessoas, apostamos no futuro de Angola </strong>
</div>
<H1>
<div id="title">
BAS<br>
LER 
</div>

</H1>
</BODY>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

</HTML>

app/views/clients/index.html.erb
 <%= stylesheet_link_tag    'clients', media: 'all', 'data-turbolinks-track': 'reload' %>
 <br>
 <br>
  <br>
 <br>
  <br>
<div class="container" align="center" style="  padding-top: 12.5px;">
  <div class="row" align="center">
      <div class="thumbnail">
        <%= image_tag("lgr-customers-unitel.jpg", :alt => "protector", :size => "50x40") %>
          <div class="caption" align="center">
            <p>Unitel - 2013</p>
          </div>
        </a>
      </div>
      <div class="thumbnail">
                <%= image_tag("c7a457f01a93bfe5e42c62a264bb65a5.jpg", :alt => "protector", :size => "50x40") %>
          <div class="caption" align="center">
            <p>Banco Bic - 2010</p>
          </div>
        </a>
      </div>  
      <div class="thumbnail">
         <%= image_tag("unnamed.png", :alt => "protector", :size => "50x40") %>
          <div class="caption" align="center">
            <p>Banco Caixa Geral - 2010</p>
          </div>
        </a>
      </div>
      <div class="thumbnail">
         <%= image_tag("urrramed.png", :alt => "protector", :size => "50x40") %>
          <div class="caption" align="center">
            <p>Bpc - 2007</p>
          </div>
        </a>
      </div>
      <div class="thumbnail">
         <%= image_tag("60464-edp.png", :alt => "protector", :size => "50x40") %>
          <div class="caption" align="center">
            <p>Edp - 2001</p>
          </div>
        </a>
      </div>
    </div>
</div>
<br>
<br>
<br>
<br>
 <br>
 <br>
  <br>
   <br>
<br>
 <br>
 <br>
  <br>
   <br> 

app/views/contacts/create.html.erb
	<%= stylesheet_link_tag    'contacts', media: 'all', 'data-turbolinks-track': 'reload' %>
<div>

</div>

app/views/contacts/new.html.erb
<%= stylesheet_link_tag    'contacts', media: 'all', 'data-turbolinks-track': 'reload' %>


<div align="center">
<div style=" width: 900px;  height: 900px; " align="center">
<br>
<h1 style="color: white; font-family: 'Roboto', sans-serif; font-size: 60px;" class="text-success"> Envie-nos um email ! </h1>
<%= simple_form_for @contact, :html => {:class => 'form-vertical'} do |f| %>
<br>
<%= f.input :name, :require => true, :required => true, :input_html => {:style=> 'width: 100%; color: black;'} %>
<br>
<%= f.input :email, :require => true, :required => true, :input_html => { :style=> 'width: 100%; color: black;'} %>
<br>
<br>
<br>
<%= f.input :message, :as => :text, :required => true, :input_html => {:rows => 9, :style => 'width: 900px;'} %>
<div>
</br>
<%= f.button :submit, 	"Enviar" %>
</div>
<% end %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Basler</title>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag '1600.ico' %>
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <link href="https://fonts.googleapis.com/css?family=Abril+Fatface|PT+Sans" rel="stylesheet"> 
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
 <link href="https://fonts.googleapis.com/css?family=Arbutus+Slab" rel="stylesheet"> 
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->
      <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <ul class="nav navbar-nav">
     <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "Basler", root_path %></li>
            <li class="<%= 'active' if current_page?(services_path) %>"><%= link_to "Serviços", services_path %></li>
              <li class="<%= 'active' if current_page?(clients_path) %>"><%= link_to "Clientes", clients_path %></li>
              <li class="<%= 'active' if current_page?(contacts_path) %>"><%= link_to "Mensagem", contacts_path %></li>
               <li class="<%= 'active' if current_page?(about_path) %>"><%= link_to "Sobre", about_path %></li>
    </ul>
   <!--<button class="btn btn-danger navbar-btn">Email</button>-->
  </div>
</nav>  
  </head>
  <body>
    <% flash.each do  |key, value |%>
    <div class='alert alert-<%= key %> alert-dismissible'><a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <%= value  %> 
    </div>
    <% end %>

    <%= yield %>

  <div id="contact-field">    
   <table align="left"> 
      <%= image_tag("190587-people-culture (1).png", :alt => "rss feed" , :size => "250x250", :style => "opacity:0.8;filter:alpha(opacity=40); float: left;") %>  
  <tr>
    <th></th>
    <th>Produtos</th> 
    <th>Localização</th>
    <th>Contacto</th>
  </tr>
  <tr>
    <td></td>
    <td>Hikvision</td> 
    <td>Luanda Mayanga</td>
    <td>+244 912 200 977</td>
  </tr>
  <tr>
    <td></td>
    <td>HP</td> 
    <td>Namibia Windhoek</td>
    <td>+244 222 331 601</td>
  </tr>
  <tr>
    <td></td>
    <td>Cisco</td> 
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td>D-Link</td> 
    <td></td>
    <td></td>
  </tr>
  <tr>  
    <td></td>
    <td> SWITCH</td>  
    <td></td>
    <td></td>
  </tr>
</table>
<br>
<br>
 <div align="center">
  <small>Copyright © 2018 BASLER LTD. All rights reserved.</small>
</div>
  </div>

  </body>
</html>

app/views/mapas/_form.html.erb
<%= form_with(model: mapa, local: true) do |form| %>
  <% if mapa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mapa.errors.count, "error") %> prohibited this mapa from being saved:</h2>

      <ul>
      <% mapa.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude, id: :mapa_latitude %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude, id: :mapa_longitude %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :mapa_address %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :mapa_description %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :mapa_title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/mapas/edit.html.erb
<h1>Editing Mapa</h1>

<%= render 'form', mapa: @mapa %>

<%= link_to 'Show', @mapa %> |
<%= link_to 'Back', mapas_path %>

app/views/mapas/index.html.erb
 <!DOCTYPE html>
 <html>
 <head>
     <script type="text/javascript">
      var map;
      function initMap() {
        map = new google.maps.Map(document.getElementById('map'), {
          center: {lat: -8.839, lng: 13.289},
          zoom: 5
        });
      }
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD7n6Gzb5I33aWaNGIP-bVbz9n1Q4nEkhM&callback=initMap"
    async defer></script>
        <style>
      /* Always set the map height explicitly to define the size of the div
       * element that contains the map. */
      #map {
         height: 120%;


      }
      /* Optional: Makes the sample page fill the window. */
      html, body {
        height: 120%;
      }
    </style>

 
 </head>

 <body>

     <div id="map">
     </div>
 
 </body>
 </html>

app/views/mapas/new.html.erb
<h1>New Mapa</h1>

<%= render 'form', mapa: @mapa %>

<%= link_to 'Back', mapas_path %>

app/views/mapas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Latitude:</strong>
  <%= @mapa.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @mapa.longitude %>
</p>

<p>
  <strong>Address:</strong>
  <%= @mapa.address %>
</p>

<p>
  <strong>Description:</strong>
  <%= @mapa.description %>
</p>

<p>
  <strong>Title:</strong>
  <%= @mapa.title %>
</p>

<%= link_to 'Edit', edit_mapa_path(@mapa) %> |
<%= link_to 'Back', mapas_path %>

app/views/services/index.html.erb
<div id="servicos" style="color: white; " >
<br>
<br>
<br>
<div id="espaçamento" style="padding-left: 10%;">
<h2> Desenvolvimento de sistemas de informação</h2><br>
<div id="tabela" style="background-color: #202020; border-radius: 3px;  width: 50%; height: 280px; border-bottom: 30px solid white;">
    BASLER está capacitada para a concepção e desenvolvimento de sistemas de informação de grande porte nas tecnologias<strong> Java Enterprise Edition e .NET Framework.</strong><br> 
<br>
BASLER adquiriu recentemente conhecimentos na área de Busines Intelligence sobre a plataforma<strong> MicroStrategy</strong>, sendo neste momento capacitada para o desenho e desenvolvimento de sistemas de apoio a decisão.<br>
<br>
BASLER dedica-se também ao desenvolvimento de software a medida, seja recorrendo ao modelo cliente/servidor, sistemas distribuídos, aplicações, soluções informáticas, etc.<br> 
</div>
</div>
<br>
<br>
<br>
<div id="espaçamento" style="padding-right: 10%;">
<h2 align="right" style="padding-right: 10%;">Manutenção de Computadores</h2><br>
<div id="tabela" style="background-color: #202020; border-radius: 3px;  width: 50%;float:right; height: 270px;  border-bottom: 30px solid white;">
Formatação;<br>
Remoção de Vírus;<br>
Recuperação da Informação.<br>
Troca e limpeza de periférico.<br>
Formação in job em rede cisco<br>
Acessórias em rede cisco a pedido do cliente.<br>
<br>
Manutenção e Instalação de;
Impressoras (em rede e USB) e outros tipos de equipamentos;
Formatação de Sistema Operacional — Configurações;
Manutenção e montagem de micro computadors
</div>
</div>
<br>
<br>
<br>
<div id="espaçamento" style="padding-left: 10%;">
<h2>Conectividade</h2><br>
<div id="tabela" style="background-color: #202020; border-radius: 3px;  width: 30%; margin-right: 30px; height: 250px;  border-bottom: 30px solid white;">
    Verificando-se a nível da tecnologia da informação o abandono dos grandes computadores (main frame) a favor das redes de computadores do tipo PC, fenómeno que se convencionou chamar down sizing, a BASLER viu-se na necessidade de se especializar na concepção, implementação e interligação deedes de computadores com diferentes arquitecturas, bem como a prestação de serviços Internet.<br>
</div>
</div>
<br>
<br>
<br>
<div id="espaçamento" style="padding-left: 5%;">
<h2>Serviços Internet/Intranet.</h2><br>
<div id="tabela" style="background-color: #202020; border-radius: 3px; width: 80%; margin-right: 30px; height: 430px;  border-bottom: 30px solid white;">
A Internet tem-se revelado como um dos desenvolvimentos mais poderosos no domínio das tecnologias da informação, informática e telecomunicações.<br>
<br>
No nosso país apesar do relativo atraso tecnológico a que estamos submetidos, a Internet tem conhecido constituído foco da atenção de todos os sectores da actividade nacional.<br>
<br>
BASLER está capacitada a oferecer um serviço completo no domínio das tecnologias associadas a Internet,<br> orgulhando-se de poder oferecer ao público Angolano a possibilidade de poder dispor localmente de um serviço completo de soluções para Internet e/ou Intranet,<br> com base na tecnologia Windows ou LINUX com destaque para:<br>
<br>
Registo de nomes (domain name) na Internet<br>
Instalação e configuração dos Serviços para Provedor Internet, para acesso corporativo a Internet ou Intranet, usando tecnologia Windows, serviços que incluem a instalação e configuração das seguintes tecnologias:
Servidor de Resolução de Nomes DNS Serverquer para domínios internos como na Internet.<br>
Servidor de Páginas e Transferência de Ficheiros (WWW+FTP).<br> 
Servidor de Correio Electrónico (serviços SMTP, POP, POP3)<br>
Segurança (firewall) e Cache de páginas web.<br>
Servidor de Acessos Remotos a Internet/Intranet.<br>

</div>
</div>
<br>
<br>
<br>
<div id="espaçamento" style="padding-right: 10%;">
<h2 align="right" style="padding-right: 5%;">Comunicações sem fios (Wireless)</h2><br>
<div id="tabela" style="background-color: #202020; border-radius: 3px; width: 80%; float:right; height: 450px;  border-bottom: 30px solid white;">
    Não se pode falar de conectividade, Internet, Metropolitan Area Network (MAN), Wide Area Network (WAN), sem que se tenha em conta a respectiva componente de comunicações.<br>
    <br>
    A implementação deste tipo de serviços passa pelo estabelecimento de links de comunicações de dados entre redes locais (LAN’s) geograficamente dispersas constituído com ou sem acesso a Internet.<br>
<br>
Pretendendo por um lado oferecer uma alternativa ao serviço prestado pela Angola-Telecom e de<br> outros provedores, e por outro procurando complementar esse serviço, a BASLER põe a<br> disposição do público um serviço completo de<br>
comunicações com base em tecnologia sem fios, que vai desde a transmissão de dados, ao estabelecimento de redes<br> privadas de telefonia (tecnologia VOIP) com possibilidades de ligação a rede pública.<br>
Redes wireless indoor e outdoor:<br>
Sistemas ponto-a-ponto; proporcionando conectividade entre dois pontos específicos.<br>
Sistemas ponto-multi-ponto; normalmente usando uma base central de comunicações que interliga vários pontos remotos.
</div>
</div>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<div id="espaçamento" style="padding-left: 10%;">
<h2>Sistemas de recepção e emissão via satélite (Vsat e VipSat)</h2><br>
<div id="tabela" style="background-color: #202020; border-radius: 3px; width: 70%;height: 300px;  border-bottom: 30px solid white; ">
    Em Angola, as distancias entre os nós de processamento informático podem implicar milhares de quilómetros, localidades em áreas onde não estão disponíveis as tecnologias necessárias para a conectividade.<br> 
<br>
Lá onde se torna inviável qualquer dos outros meios de comunicações, oferecemos links de comunicação via satélite garantindo assim a conectividade onde quer que seja necessário.<br>
<br>
Neste domínio oferecemos:<br>
Links VipSat – proporcionado o acesso a Internet com a largura de banda adequada.<br> Usando esta tecnologia é possível estabelecer uma ligação ponto a ponto estabelecendo redes privadas virtuais (VPN).<br>
<br>
Sistemas VSAT privados – constituindo redes privadas interligando vários pontos oferecendo a possibilidade de gestão própria.<br> Carateriza-se por anular a necessidade do “chanto duplo salto” na comunicação entre dois pontos específicos.<br>
</div> 
</div>  
<br>
<br>
<br>
<br>
<br>
<div id="aligment" style="padding-left: 50%;" >
<h2> Redes Locais de computadores, (LAN)</h2>
<div id="tabela" style="background-color: #202020; border-radius: 3px; width: 80%; height: 400px;  border-bottom: 30px solid white;">
Componente básica para a construção MAN's, WAN's ou acesso corporativo a Internet,<br> BASLER conta com uma larga experiência em: <br>
Desenho, montagem e manutenção de redes informáticas para intranets e internet: <br>
<br>
Estes serviços são prestados seguindo a risca o conjunto de standards TIA/EIA-568-B (ANSI/TIA/EIA-568-B.1-2001, -B.2-2001, e -B.3-2001) que definem como desenhar e implementar sistemas de cablagem estruturada.<br> 
<br>
Estes standards definem tipos de cabos, distancias, conectores, arquitecturas de cablagem estruturada, terminações<br> e características de performance, requisitos para a instalação e métodos para a testar a cablagem estruturada
 efectuado tanto para sistemas de par trançado (CAT6), como para sistemas de fibra óptica.<br>
<br>
Certificação e Classificação de redes com tecnologia Fluke. <br>
</div>
</div>
<br>
<br>
<br>
<div id="aligment" style="padding-left: 20%;" >
<h2>Redes metropolitanas (MAN) e alargadas (WAN)</h2><br>
<div id="tabela" style="background-color: #202020; border-radius: 3px; width: 80%; height: 300px; border-bottom: 30px solid white;">
As redes metropolitanas são formadas pela interligação de várias LAN's se estendem 	pelo mesmo perímetro urbano. A rede é considerada alargada quando interliga várias LAN's e/ou MAN's que situados em perímetros urbanos diferentes ou separadas por distâncias consideráveis (várias centenas ou mais de quilómetros).<br>
<br>
BASLER aconselha a opção de links privados implementados com tecnologia wireless para os links urbanos e a utilização de tecnologia VSAT para os links interurbanos.<br>
<br>
Cada LAN que se pretenda incorporar a MAN/WAN será servida por um Wireless Router (Roteador ou encaminhador de dados), responsável por garantir a ligação com as outras LAN/MAN/WAN.<br>
<br>
Opcionalmente, é possível adicionar dispositivos que permitem serviços de voz (VOIP) entre quaisquer pontos do Sistema.<br>Estes serviços de voz podem implementar redes telefónicas privadas que compreendam PBXs, Faxes e outras facilidades.<br>
</div>
</div>
<br>
<br>
<br>
<div id="aligment" style="padding-left: 10%;" >
<h2>Montagem de câmaras de segurança.</h2><br>
<div id="tabela" style="background-color: #202020; border-radius: 3px; width: 40%; height: 130px; border-bottom: 30px solid white;">
Buscando a redução de custos e qualidade nos serviços, BASLER atua com grande força na montagem e manutenção dos sistemas.<br>
</div>
</div>
<br>
<br>
<br>
<div id="aligment" style="padding-left: 10%;" >
<h2>Instalação e Montagem de Sistemas Eléctricos.</h2><br>
<div id="tabela" style="background-color: #202020; border-radius: 500px solid white; width: 80%; border-left: 50%; border-bottom: 30px solid white;">

Projectos de instalação e montagem de sistemas eléctricos
<p> Instalações em baixa tensão.</p>

Montagem e manutenção de Instalações residenciais<br>
Montagem e manutenção de Instalações comerciais<br>
Montagem e manutenção de Instalações industriais<br>
Montagem e manutenção de rede de iluminação pública<br>
Montagem e manutenção de geradores<br>
Montagem, reparação, configuração e manutenção de UPS<br>


<strong> Instalações em média tensão </strong>
Montagem e manutenção de linhas de MT<br>
Montagem e manutenção de PT<br>
</div>
</div>
<br>
<br>
<br>
</div>
</div>